# Generated by Django 4.0.4 on 2022-05-03 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_created_at',
            field=models.TimeField(default=datetime.datetime(2022, 5, 3, 8, 48, 53, 67954)),
        ),
    ]
