# Generated by Django 4.0.4 on 2022-05-29 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_message_time_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='slug',
        ),
        migrations.AlterField(
            model_name='message',
            name='time_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 9, 53, 48, 919436)),
        ),
    ]
